# Install system apt packages
- hosts: tob_azure
  become: yes
  become_method: sudo
  tasks:
    - name: Install Git
      apt: name=git state=latest

# CLONE THE REPO
- hosts: tob_azure
  become: yes
  tasks:
    - name: clone repo
      git:
        repo: "https://github.com/{{ github_user }}/{{ app_name }}.git"
        dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
        update: yes # Does a git pull if the repo already exists
        force: yes

# Copy the config file
- hosts: tob_azure
  become: yes
  become_method: sudo
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./config.ts
        dest: /home/{{ ansible_ssh_user }}/{{ app_name }}/
        owner: tob
        group: tob
        mode: "0644"

    #INSTALL DOCKER
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Update apt and install docker.io
      apt: update_cache=yes name=docker.io state=latest

# Build
- hosts: tob_azure
  become: yes
  become_method: sudo
  tasks:
    - name: Build the docker image
      shell: chdir=/home/{{ ansible_ssh_user }}/{{ app_name }} docker build . -t tob

# RUN
- hosts: tob_azure
  become: yes
  become_method: sudo
  tasks:
    - name: Kill the container jojo
      shell: docker kill jojo

    - name: Remove the container jojo
      shell: docker rm jojo

    - name: Rebuild the container
      shell: docker run --name jojo -itd tob
